version: 2
jobs:
 python_deploy:
    docker:
    # Primary container image where all steps run.
     - image: amitkhomane/flaskapp

    steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: python app.py &
 cypress_test:
    docker:
      - image: cypress/base:10
    parallelism: 4
    steps:
      - checkout
      # note: omitting caching for brevity
      # quickly install NPM dependencies
      - run: npm ci
      # load balance all tests across 4 CI machines
      - run: $(npm bin)/cypress run --parallel


