version: 2
jobs:
 build:
    docker:
    # Primary container image where all steps run.
     - image: amitkhomane/flaskapp

    steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: python app.py
     - run: curl http://localhost:8080 


